# Generated by Django 4.0.6 on 2022-09-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quizmodels',
            name='answer',
            field=models.CharField(choices=[('opt1', 'opt1'), ('opt2', 'opt2'), ('opt3', 'opt3'), ('opt4', 'opt4')], max_length=255),
        ),
    ]
