# Generated by Django 4.0.6 on 2022-09-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userinfomodel_alter_quizmodels_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResulModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.userinfomodel')),
            ],
        ),
    ]
