# Generated by Django 4.0.6 on 2022-09-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizresulmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
