# Generated by Django 4.0.6 on 2022-09-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_userinfomodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
