# Generated by Django 4.0.6 on 2022-09-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_userinfomodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
